### ISSUE TITLE
[SUGGESTION] Add possibility for more than 1 fake connection

### ISSUE THREAD

**Issue by DinoNuggets2** [CedModV2/SCPSLAudioApi#1]
I’m not sure if a separate plugin dev would have to do this using the api, but if this does relate to the api:
Add a way to have more than one fake connection. This way more than one audio can be played at the same time.
It would probably be easier as well since Northwood added an option to enable/disable intercom for anyone

**Comment by ced777ric** [comment]
Connection stuff and dummies are handled by the plugin using the api.
